sudo: required

language: javascript

services:
# - docker

before_install:
 - cd front; TRAVIS_BUILD_DIR=`pwd`
 - npm install
# - docker build -t mosquitto -f back/Dockerfile .
# - docker run -d -p 1883:1883 -p 9001:9001 mosquitto

script: 
 - to 'npm test'
# - docker run -t -v `pwd`:/build mosquitto /build/tests/integration.sh
# - true
