sudo: required

language: javascript

services:
 - docker

before_install:
 - docker build -t mosquitto -f back/Dockerfile .
# - docker run -d -p 1883:1883 -p 9001:9001 mosquitto

script: 
 - docker build -t mosquitto -f back/Dockerfile . 
#- true
